### ISSUE TITLE
按钮标签显示问题

### ISSUE THREAD

**Issue by deluxghost** [Cloud-Swift/SKE#5]
![image](https://user-images.githubusercontent.com/5835759/58467066-8720c180-816d-11e9-905f-f4ab74aaeb4c.png)

Chrome stable latest, macOS Mojave

**Comment by umaim** [comment]
记得好像，确实是显示不完，就显示`...`省略了
只有长一点的字符有这个问题
中文应该还好。
对此，加入了 `hover` tip 显示完整文字

不知道可否有更好的解决方案

**Comment by deluxghost** [comment]
中文倒是没什么问题

看起来按钮也不是固定宽度啊，我觉得让按钮自动变宽一点也好，毕竟，只显示三/四个字母也太寒酸了，在我的截图里面 COPY 总共四个字母还被省略一个
