### ISSUE TITLE
i18n 文本

### ISSUE THREAD

**Issue by deluxghost** [Cloud-Swift/SKE#6]
似乎加上空格比较好：

https://github.com/PixvIO/SKE/blob/888f948964033b0c0dc8a5bb0a099ad0a5d67f21/js/app.js#L43-L44

https://github.com/PixvIO/SKE/blob/888f948964033b0c0dc8a5bb0a099ad0a5d67f21/js/app.js#L57-L58

这么多空格有作用吗：

https://github.com/PixvIO/SKE/blob/888f948964033b0c0dc8a5bb0a099ad0a5d67f21/js/app.js#L68-L70

**Comment by umaim** [comment]
很多空格貌似是没有这些空格，按钮的文字样式并不统一（年代有些久远，为什么这么写有些模糊了

只的是 `%X%` 的前后加空格么？

**Comment by deluxghost** [comment]
%X% 前后和 Key 前吧

而一堆 nbsp 实在是看不懂…… 🤣
